- name: Install xfce4 stuff
  apt:
    pkg:
      - xfce4
      - xfce4-goodies
      - xorg
      - dbus-x11
      - x11-xserver-utils
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - cloudvm
    - cloudvm-xfce4-install
