# 
# XRDP installation and setup
#

- name: Install xrdp
  apt:
    pkg:
      - xrdp
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - cloudvm
    - cloudvm-xrdp-install

- name: Setup custom parameters for xrdp
  lineinfile:
    dest: '{{ item.configfile }}'
    state: present
    regexp: "^{{ item.key }}="
    insertafter: '^\[{{ item.section }}\]$'
    line: "{{ item.key }}={{ item.value }}"
  with_items:
    - {key: AllowRootLogin , value: 'false', section: Security , configfile: /etc/xrdp/sesman.ini}
    - {key: MaxSessions , value: 2, section: Sessions , configfile: /etc/xrdp/sesman.ini}
    - {key: KillDisconnected , value: 'true', section: Sessions , configfile: /etc/xrdp/sesman.ini}
  tags:
    - cloudvm
    - cloudvm-xrdp-install
  notify:
    - Restart xrdp


- name: Append group ssl-cert to xrdp user
  user:
    name: xrdp
    groups: ssl-cert
  tags:
    - cloudvm
    - cloudvm-xrdp-install

- name: Configure xrdp to run xfce on localhost
  block:
    - name: Install xfce4
      include_tasks: xfce4-install.yml

    - name: Configure xrdp with xfce4
      lineinfile:
        path: /etc/xrdp/xrdp.ini
        line: 'exec startxfce4'
      notify:
        - Restart xrdp
  when: xrdp_desktopenvironment == 'xfce'
  tags:
    - cloudvm
    - cloudvm-xrdp-install

